-- AUTO-GENERATED by scripts/upload_enemy_assets.py
-- DO NOT EDIT MANUALLY. Regenerate after mesh updates.
-- Asset type: Model (Open Cloud). Consumed via InsertService:LoadAsset
-- in EnemyRigs.tryCloneMesh (server-side, cached per enemy type).
return {
	Pocong = "rbxassetid://107709794090664",
	Kuntilanak = "rbxassetid://111406860449904",
	Leak = "rbxassetid://132001837103239",
	Genderuwo = "rbxassetid://139769722361283",
	Tuyul = "rbxassetid://95757886711287",
	SundelBolong = "rbxassetid://125519017691944",
	Banaspati = "rbxassetid://104731812028934",
	WeweGombel = "rbxassetid://111119714324258",
	ButoIjo = "rbxassetid://125648166362876",
	SetanPasar = "rbxassetid://117928888067153",
	NagaKomodo = "rbxassetid://105785756477318",
	BuddhaWraith = "rbxassetid://111346628317618",
}
