#!/usr/bin/env python3
"""
Phase B: re-upload normalized setan FBX to Roblox Open Cloud, updating the
EXISTING asset IDs in place via PATCH (so rbxassetid:// references in
EnemyMeshIds.lua stay valid). Falls back to POST (new asset) only if PATCH is
unsupported, and rewrites EnemyMeshIds.lua for any changed IDs.

USAGE (repo root):
    .venv\\Scripts\\python scripts\\reupload_setan_assets.py
    .venv\\Scripts\\python scripts\\reupload_setan_assets.py --single Pocong

Credentials from gitignored .env (ROBLOX_API_KEY, OWNER_USER_ID). Key is never
printed (only ...last4). Asset IDs are public references (safe to log).
"""
import os
import re
import sys
import json
import time
import argparse

import requests
from dotenv import load_dotenv

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_PATH = os.path.join(REPO, ".env")
ASSETS_DIR = os.path.join(REPO, "assets", "enemies")
MODULE_PATH = os.path.join(REPO, "src", "shared", "EnemyMeshIds.lua")

ENEMIES = [
    "Pocong", "Kuntilanak", "Leak", "Genderuwo", "Tuyul", "SundelBolong",
    "Banaspati", "WeweGombel", "ButoIjo", "SetanPasar", "NagaKomodo", "BuddhaWraith",
]

ASSETS_BASE = "https://apis.roblox.com/assets/v1/assets"
OP_ENDPOINT = "https://apis.roblox.com/assets/v1/operations/{}"
SLEEP_BETWEEN = 3
POLL_INTERVAL = 2
POLL_TIMEOUT = 60
RETRIES = 3


def log(m):
    print(m, flush=True)


def load_creds():
    load_dotenv(ENV_PATH)
    key = os.environ.get("ROBLOX_API_KEY")
    uid = os.environ.get("OWNER_USER_ID")
    if not key or not uid:
        log("ERROR: ROBLOX_API_KEY / OWNER_USER_ID missing in .env")
        sys.exit(1)
    log(f"creds loaded (key ...{key[-4:]}, userId {uid})")
    return key, uid


def parse_ids():
    ids = {}
    if os.path.exists(MODULE_PATH):
        with open(MODULE_PATH, encoding="utf-8") as f:
            for m in re.finditer(r'(\w+)\s*=\s*"rbxassetid://(\d+)"', f.read()):
                ids[m.group(1)] = m.group(2)
    return ids


def write_module(ids):
    lines = [
        "-- AUTO-GENERATED by scripts/upload_enemy_assets.py",
        "-- DO NOT EDIT MANUALLY. Regenerate after mesh updates.",
        "-- Asset type: Model (Open Cloud). Consumed via InsertService:LoadAsset",
        "-- in EnemyRigs.tryCloneMesh (server-side, cached per enemy type).",
        "return {",
    ]
    for n in ENEMIES:
        if n in ids:
            lines.append(f'\t{n} = "rbxassetid://{ids[n]}",')
    lines.append("}")
    lines.append("")
    with open(MODULE_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def poll_operation(op_id, key):
    deadline = time.time() + POLL_TIMEOUT
    while time.time() < deadline:
        time.sleep(POLL_INTERVAL)
        try:
            pr = requests.get(OP_ENDPOINT.format(op_id), headers={"x-api-key": key}, timeout=20)
        except Exception:
            continue
        if pr.status_code != 200:
            continue
        pj = pr.json()
        if pj.get("done"):
            return (pj.get("response") or {}).get("assetId")
    return None


def _multipart(name, uid, data, desc, asset_id=None):
    req = {
        "assetType": "Model",
        "displayName": f"{name}Mesh",
        "description": desc,
        "creationContext": {"creator": {"userId": str(uid)}},
    }
    if asset_id is not None:
        # PATCH (update) requires assetId in body to match the URL.
        req["assetId"] = str(asset_id)
    return {
        "request": (None, json.dumps(req), "application/json"),
        "fileContent": (name + ".fbx", data, "model/fbx"),
    }


def post_new(name, key, uid, data):
    """Fallback: create a brand-new asset, return its id."""
    for attempt in range(1, RETRIES + 1):
        r = requests.post(ASSETS_BASE, headers={"x-api-key": key},
                          files=_multipart(name, uid, data, f"PUSAKA Pasar Gaib - {name} realistic Sketchfab asset"),
                          timeout=180)
        if r.status_code == 429 or r.status_code >= 500:
            time.sleep(2 ** attempt)
            continue
        if r.status_code not in (200, 201):
            return None, f"POST HTTP {r.status_code}: {r.text[:300]}"
        op = r.json()
        op_id = op.get("path", "").split("/")[-1] or op.get("operationId")
        aid = poll_operation(op_id, key) if op_id else (op.get("response") or {}).get("assetId")
        return (aid, None) if aid else (None, "POST poll timeout")
    return None, "POST failed after retries"


def patch_one(name, asset_id, key, uid):
    """PATCH existing asset content. Returns (new_id, status, err).
    status in {PATCHED, POSTED_NEW, SKIP, STOP}."""
    fbx = os.path.join(ASSETS_DIR, name + ".fbx")
    if not os.path.exists(fbx):
        return asset_id, "SKIP", "FBX missing"
    with open(fbx, "rb") as f:
        data = f.read()
    url = f"{ASSETS_BASE}/{asset_id}"
    desc = f"PUSAKA Pasar Gaib - {name} realistic Sketchfab asset"

    for attempt in range(1, RETRIES + 1):
        try:
            r = requests.patch(url, headers={"x-api-key": key},
                               files=_multipart(name, uid, data, desc, asset_id=asset_id), timeout=180)
        except Exception as e:
            log(f"  [{name}] PATCH attempt {attempt} exception: {e!r}")
            time.sleep(2 ** attempt)
            continue

        if r.status_code == 429:
            log(f"  [{name}] 429 rate limit, sleep 5s")
            time.sleep(5)
            continue
        if r.status_code >= 500:
            log(f"  [{name}] {r.status_code} server error, backoff {2 ** attempt}s")
            time.sleep(2 ** attempt)
            continue
        if r.status_code == 405:
            log(f"  [{name}] PATCH 405 unsupported -> fallback POST (new id)")
            new_id, err = post_new(name, key, uid, data)
            if new_id:
                return new_id, "POSTED_NEW", None
            return asset_id, "SKIP", f"fallback POST failed: {err}"
        if r.status_code == 403:
            return asset_id, "STOP", f"403 ownership/permission: {r.text[:300]}"
        if r.status_code == 400:
            return asset_id, "SKIP", f"400 (locked/moderation/format): {r.text[:300]}"
        if r.status_code not in (200, 201):
            return asset_id, "SKIP", f"HTTP {r.status_code}: {r.text[:300]}"

        op = r.json()
        op_id = op.get("path", "").split("/")[-1] or op.get("operationId")
        aid = poll_operation(op_id, key) if op_id else (op.get("response") or {}).get("assetId")
        if aid:
            return aid, "PATCHED", None
        return asset_id, "SKIP", "PATCH poll timeout 60s"
    return asset_id, "SKIP", "PATCH failed after retries"


def main():
    ap = argparse.ArgumentParser(description="PATCH setan assets in Roblox Open Cloud")
    ap.add_argument("--single", metavar="NAME", help="only this setan")
    args = ap.parse_args()

    key, uid = load_creds()
    ids = parse_ids()
    if not ids:
        log("ERROR: no IDs in EnemyMeshIds.lua")
        sys.exit(1)

    targets = [args.single] if args.single else list(ENEMIES)
    summary = []
    changed = False
    for name in targets:
        asset_id = ids.get(name)
        if not asset_id:
            log(f"[{name}] no existing id, skip")
            summary.append({"name": name, "status": "SKIP", "err": "no id"})
            continue
        log(f"[{name}] PATCH asset {asset_id} ...")
        new_id, status, err = patch_one(name, asset_id, key, uid)
        summary.append({"name": name, "status": status, "old_id": asset_id, "new_id": new_id, "err": err})
        if status == "STOP":
            log(f"[{name}] STOP: {err}")
            log("Aborting batch (ownership/permission error). Fix API key scope.")
            break
        if status == "POSTED_NEW" and new_id and new_id != asset_id:
            ids[name] = new_id
            changed = True
            log(f"[{name}] new id {new_id} (was {asset_id})")
        elif status == "PATCHED":
            log(f"[{name}] PATCHED ok (id {new_id})")
        else:
            log(f"[{name}] {status}: {err}")
        time.sleep(SLEEP_BETWEEN)

    if changed:
        write_module(ids)
        log(f"=== rewrote EnemyMeshIds.lua (fallback POST changed some ids) ===")
    else:
        log("=== EnemyMeshIds.lua unchanged (all PATCH in place) ===")
    log("SUMMARY=" + json.dumps(summary))


if __name__ == "__main__":
    main()
