#!/usr/bin/env python3
"""
Upload PUSAKA enemy FBX assets to Roblox Open Cloud, then regenerate the
ReplicatedStorage.Shared.EnemyMeshIds Lua module.

Assets are uploaded as `Model` type (Open Cloud Assets API only supports
Model for FBX). The resulting asset IDs are consumed at runtime via
InsertService:LoadAsset in EnemyRigs.tryCloneMesh (server-side, cached).

SETUP (once, from repo root):
    uv venv
    uv pip install requests python-dotenv

USAGE (from repo root):
    .venv\\Scripts\\python scripts\\upload_enemy_assets.py              # upload missing only (default)
    .venv\\Scripts\\python scripts\\upload_enemy_assets.py --single Leak
    .venv\\Scripts\\python scripts\\upload_enemy_assets.py --regenerate      # force re-upload all
    .venv\\Scripts\\python scripts\\upload_enemy_assets.py --regenerate-fbx  # re-run Blender gen first

Credentials are read from .env (ROBLOX_API_KEY, OWNER_USER_ID). The API key
is NEVER printed. .env is gitignored.
"""
import os
import sys
import json
import time
import re
import shutil
import argparse
import subprocess

import requests
from dotenv import load_dotenv

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_PATH = os.path.join(REPO, ".env")
ASSETS_DIR = os.path.join(REPO, "assets", "enemies")
MODULE_PATH = os.path.join(REPO, "src", "shared", "EnemyMeshIds.lua")
GEN_SCRIPT = os.path.join(REPO, "scripts", "generate_enemy_fbx.py")

# Canonical order = matches Constants.ENEMIES keys.
ENEMIES = [
    "Pocong", "Kuntilanak", "Leak", "Genderuwo", "Tuyul", "SundelBolong",
    "Banaspati", "WeweGombel", "ButoIjo", "SetanPasar", "NagaKomodo", "BuddhaWraith",
]

ASSETS_ENDPOINT = "https://apis.roblox.com/assets/v1/assets"
OP_ENDPOINT = "https://apis.roblox.com/assets/v1/operations/{}"
POLL_INTERVAL = 2
POLL_TIMEOUT = 60
SLEEP_BETWEEN = 2
RETRIES = 3


def log(m):
    print(m, flush=True)


def load_creds():
    load_dotenv(ENV_PATH)
    key = os.environ.get("ROBLOX_API_KEY")
    uid = os.environ.get("OWNER_USER_ID")
    if not key or not uid:
        log("ERROR: ROBLOX_API_KEY / OWNER_USER_ID missing in .env")
        sys.exit(1)
    return key, uid


def parse_existing_ids():
    ids = {}
    if os.path.exists(MODULE_PATH):
        with open(MODULE_PATH, encoding="utf-8") as f:
            txt = f.read()
        for m in re.finditer(r'(\w+)\s*=\s*"rbxassetid://(\d+)"', txt):
            ids[m.group(1)] = m.group(2)
    return ids


def upload_one(name, key, uid):
    fbx = os.path.join(ASSETS_DIR, name + ".fbx")
    if not os.path.exists(fbx):
        return None, f"FBX missing: {fbx}"
    req = {
        "assetType": "Model",
        "displayName": f"{name}Mesh",
        "description": f"PUSAKA Pasar Gaib - {name} enemy mesh",
        "creationContext": {"creator": {"userId": str(uid)}},
    }
    with open(fbx, "rb") as f:
        data = f.read()

    for attempt in range(1, RETRIES + 1):
        files = {
            "request": (None, json.dumps(req), "application/json"),
            "fileContent": (name + ".fbx", data, "model/fbx"),
        }
        try:
            r = requests.post(ASSETS_ENDPOINT, headers={"x-api-key": key}, files=files, timeout=120)
        except Exception as e:
            log(f"  [{name}] attempt {attempt}: exception {e!r}")
            time.sleep(SLEEP_BETWEEN * attempt)
            continue
        if r.status_code == 429 or r.status_code >= 500:
            log(f"  [{name}] attempt {attempt}: HTTP {r.status_code} (rate/server), backoff")
            time.sleep(SLEEP_BETWEEN * attempt)
            continue
        if r.status_code not in (200, 201):
            return None, f"HTTP {r.status_code}: {r.text[:400]}"
        op = r.json()
        op_id = op.get("path", "").split("/")[-1] or op.get("operationId")
        if not op_id:
            aid = (op.get("response") or {}).get("assetId")
            return (aid, None) if aid else (None, f"no operationId: {json.dumps(op)[:300]}")
        # poll
        deadline = time.time() + POLL_TIMEOUT
        while time.time() < deadline:
            time.sleep(POLL_INTERVAL)
            try:
                pr = requests.get(OP_ENDPOINT.format(op_id), headers={"x-api-key": key}, timeout=20)
            except Exception:
                continue
            if pr.status_code != 200:
                continue
            pj = pr.json()
            if pj.get("done"):
                aid = (pj.get("response") or {}).get("assetId")
                return (aid, None) if aid else (None, f"done but no assetId: {json.dumps(pj)[:300]}")
        return None, f"poll timeout {POLL_TIMEOUT}s"
    return None, f"failed after {RETRIES} retries"


def write_module(ids):
    # Single-space around '=' to stay StyLua-compliant (no manual alignment).
    lines = [
        "-- AUTO-GENERATED by scripts/upload_enemy_assets.py",
        "-- DO NOT EDIT MANUALLY. Regenerate after mesh updates.",
        "-- Asset type: Model (Open Cloud). Consumed via InsertService:LoadAsset",
        "-- in EnemyRigs.tryCloneMesh (server-side, cached per enemy type).",
        "return {",
    ]
    for n in ENEMIES:
        if n in ids:
            lines.append(f'\t{n} = "rbxassetid://{ids[n]}",')
    lines.append("}")
    lines.append("")
    with open(MODULE_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def regenerate_fbx():
    blender = os.environ.get("BLENDER_PATH", r"C:\Program Files\Blender Foundation\Blender 4.5\blender.exe")
    tmp = os.path.join(os.environ.get("TEMP", "."), "pusaka_gen_out")
    log("=== regenerate FBX via Blender headless ===")
    if not os.path.exists(GEN_SCRIPT):
        log(f"  gen script missing: {GEN_SCRIPT} (skip)")
        return
    subprocess.run([blender, "--background", "--python", GEN_SCRIPT], check=False)
    # Blender cannot write into the repo (Documents) directly; it outputs to
    # %TEMP%\\pusaka_gen_out and this (regular python) process moves them in.
    if os.path.isdir(tmp):
        os.makedirs(ASSETS_DIR, exist_ok=True)
        for fn in os.listdir(tmp):
            if fn.endswith((".fbx", ".png")):
                shutil.move(os.path.join(tmp, fn), os.path.join(ASSETS_DIR, fn))
        log(f"  moved regenerated assets -> {ASSETS_DIR}")


def main():
    ap = argparse.ArgumentParser(description="Upload enemy FBX to Roblox Open Cloud + regen EnemyMeshIds.lua")
    ap.add_argument("--regenerate", action="store_true", help="force re-upload all (ignore existing IDs)")
    ap.add_argument("--single", metavar="NAME", help="only upload this enemy")
    ap.add_argument("--skip-blender", action="store_true", help="upload existing FBX only (default behavior)")
    ap.add_argument("--regenerate-fbx", action="store_true", help="re-run Blender FBX generation before upload")
    args = ap.parse_args()

    key, uid = load_creds()

    if args.regenerate_fbx:
        regenerate_fbx()

    existing = {} if args.regenerate else parse_existing_ids()
    targets = [args.single] if args.single else list(ENEMIES)
    if args.single and args.single not in ENEMIES:
        log(f"ERROR: unknown enemy '{args.single}'. Valid: {ENEMIES}")
        sys.exit(1)

    ids = dict(existing)
    log(f"=== UPLOAD: {len(targets)} target(s), {len(existing)} already known ===")
    uploaded, skipped, failed = 0, 0, 0
    for name in targets:
        if name in existing and not args.regenerate:
            log(f"[{name}] skip (already rbxassetid://{existing[name]})")
            skipped += 1
            continue
        log(f"[{name}] uploading...")
        aid, err = upload_one(name, key, uid)
        if aid:
            ids[name] = aid
            uploaded += 1
            log(f"[{name}] OK assetId={aid}")
        else:
            failed += 1
            log(f"[{name}] FAIL: {err}")
        time.sleep(SLEEP_BETWEEN)

    write_module(ids)
    log(f"=== DONE: uploaded={uploaded} skipped={skipped} failed={failed}; module has {len(ids)}/{len(ENEMIES)} ids ===")
    log("SUMMARY=" + json.dumps({n: ids.get(n) for n in ENEMIES}))


if __name__ == "__main__":
    main()
